# we create a Docker image from source code
version: '3.8'
services:  
  buso-database:
    image: postgres:15.0
    container_name: buso-database
    ports:
      - 5434:5432 #{port in host(myPC)} : {port in Container}
    #environment variables, like: db's username, password...
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: buso
    networks:
      - buso-network
networks:
  buso-network:
#Create container,network,...from "docker composer" file:
#-d: deamon/background mode
#docker compose up -d 
#if you want to start only specified services/container:
#docker compose up -d dev-database -d
#How to remove containers+volumes
#docker compose rm dev-database --stop --force --volumes